name: "Check PR"

on:
  pull_request:
    branches:
      - "main"
    paths:
      - "src/**"
  workflow_dispatch:

concurrency:
  group: "${{github.workflow}}-${{github.head_ref}}"
  cancel-in-progress: true

jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        # Disabling shallow clone is recommended for improving relevancy of reporting
        fetch-depth: 0
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  tests:
    name: "Run Tests"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: "Setup .NET CLI"
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "7.x"

      - name: "Restore Solution NuGets"
        run: dotnet restore

      - name: "Build Solution"
        run: dotnet build
          --no-restore
          --configuration "Release"

      - name: "Run Solution Tests"
        run: dotnet test
          --no-restore --no-build
          --configuration "Release"
          --settings "src/CodeCoverage.runsettings"
          --collect "XPlat Code Coverage"
          --logger "trx;logfileprefix=tr"

      - name: "Publish Solution Test Results"
        uses: actions/upload-artifact@v3
        if: success() || failure()
        with:
          name: "test-results"
          path: "src/**/TestResults/*.trx"
